name: SuperElytra
main: eisenwave.elytra.SuperElytraPlugin
version: 2.0

permissions:
  superelytra.glide:
    description: "allows a player enhanced gliding"
    default: true
  superelytra.launch:
    description: "allows a player to launch themselves by sneaking"
    default: true
