name: SuperElytra
main: eisenwave.elytra.SuperElytraPlugin
version: 2.2

permissions:
  superelytra.glide:
    description: "enhanced gliding"
    default: true
  superelytra.launch:
    description: "launch by sneaking"
    default: true
  superelytra.command.elytramode:
    description: "/elytramode"
    default: true

commands:
  elytramode:
    aliases: [elmode]
    permission: superelytra.command.elytramode
    description: "changes the personal elytra mode"
